Import ('env')

name = 'backbones-generator'
inc = env.Dir('../')
src = env.Glob('*.cpp')

deps = ['backbones-generator', 'gmock','gtest_main', 'gtest', 'prot-filer', 'backbones-generator-objects']

env.CreateTest(name, inc, src, deps)
