Import ('env')

name = 'backbones-generator'
inc = env.Dir('../src')
src = env.Glob('*.cpp'), env.File('../src/grillado.cpp'), env.File('../src/tree_helper.cpp'), env.File('../src/tree_filters.cpp'), env.File('../src/tree_data.cpp')
deps = ['backbones-generator', 'gmock','gtest_main', 'prot-filer']

CXXFLAGS=['-Wall', '-Wextra', '-Wno-sign-compare']
env.Replace(CXXFLAGS=CXXFLAGS, CFLAGS=CXXFLAGS)

env.CreateTest(name, inc, src, deps)
